integration of oss-fuzz in make test
The requirements for an ideal integration of a project in oss-fuzz are:
https://github.com/google/oss-fuzz/blob/master/docs/ideal_integration.md
- Is maintained by code owners in their RCS (Git, SVN, etc).
- Is built with the rest of the tests - no bit rot!
- Has a seed corpus with good code coverage.
- Is continuously tested on the seed corpus with ASan/UBSan/MSan
- Is fast and has no OOMs
- Has a fuzzing dictionary, if applicable

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -84,6 +84,9 @@ cover=0
 zprefix=0
 zconst=0
 build64=0
+with_sanitizers=0
+with_msan=0
+with_fuzzers=0
 gcc=0
 warn=0
 debug=0
@@ -114,6 +117,9 @@ case "$1" in
       echo '  configure [--const] [--zprefix] [--prefix=PREFIX]  [--eprefix=EXPREFIX]' | tee -a configure.log
       echo '    [--static] [--64] [--libdir=LIBDIR] [--sharedlibdir=LIBDIR]' | tee -a configure.log
       echo '    [--includedir=INCLUDEDIR] [--archs="-arch i386 -arch x86_64"]' | tee -a configure.log
+      echo '    [--with-sanitizers]         Build with address sanitizer and all supported sanitizers other than memory sanitizer (disabled by default)' | tee -a configure.log
+      echo '    [--with-msan]               Build with memory sanitizer (disabled by default)' | tee -a configure.log
+      echo '    [--with-fuzzers]            Build test/fuzz (disabled by default)' | tee -a configure.log
         exit 0 ;;
     -p*=* | --prefix=*) prefix=`echo $1 | sed 's/.*=//'`; shift ;;
     -e*=* | --eprefix=*) exec_prefix=`echo $1 | sed 's/.*=//'`; shift ;;
@@ -137,6 +143,9 @@ case "$1" in
     -c* | --const) zconst=1; shift ;;
     -w* | --warn) warn=1; shift ;;
     -d* | --debug) debug=1; shift ;;
+    --with-sanitizers) with_sanitizers=1; shift ;;
+    --with-msan) with_msan=1; shift ;;
+    --with-fuzzers) with_fuzzers=1; shift ;;
     *)
       echo "unknown option: $1" | tee -a configure.log
       echo "$0 --help for help" | tee -a configure.log
@@ -401,6 +410,49 @@ fi
 
 echo >> configure.log
 
+if test $with_sanitizers -eq 1; then
+    if test $with_msan -eq 1; then
+        echo "Error: --with-sanitizers and --with-msan cannot be used together"
+        exit 1
+    fi
+    echo -n "Checking for sanitizers ASan/UBSan... " | tee -a configure.log
+    sanitizers=""
+    for san in bool address array-bounds float-divide-by-zero function integer-divide-by-zero return shift signed-integer-overflow undefined unsigned-integer-overflow vla-bound vptr; do
+        if try $CC -c $CFLAGS $test.c -fsanitize=$san ; then
+            if test -n "$sanitizers"; then
+                sanitizers="$sanitizers,$san"
+            else
+                sanitizers="$san"
+            fi
+        fi
+    done
+
+    SANITIZERS_CFLAGS=""
+    if test -n "$sanitizers"; then
+        echo "-fsanitize=$sanitizers" | tee -a configure.log
+        SANITIZERS_CFLAGS="-fsanitize=$sanitizers"
+    else
+        echo No | tee -a configure.log
+        with_sanitizers=0
+    fi
+
+    echo >> configure.log
+fi
+
+if test $with_msan -eq 1; then
+    echo -n "Checking for MSan... " | tee -a configure.log
+    if try $CC -c $CFLAGS $test.c -fsanitize=memory ; then
+        echo "-fsanitize=memory" | tee -a configure.log
+        MSAN_CFLAGS="-fsanitize=memory"
+    else
+        echo No | tee -a configure.log
+        MSAN_CFLAGS=""
+        with_msan=0
+    fi
+
+    echo >> configure.log
+fi
+
 # see if shared library build supported
 cat > $test.c <<EOF
 extern int getchar();
@@ -432,6 +484,8 @@ else
   ALL="static shared"
   TEST="all teststatic testshared"
 fi
+
+TEST="$TEST run_fuzzers"
 
 # check for underscores in external names for use by assembler code
 CPP=${CPP-"$CC -E"}
@@ -863,6 +917,11 @@ echo uname = $uname >> configure.log
 sed < ${SRCDIR}Makefile.in "
 /^CC *=/s#=.*#=$CC#
 /^CFLAGS *=/s#=.*#=$CFLAGS#
+/^WITH_SANITIZERS *=/s#=.*#=$with_sanitizers#
+/^WITH_MSAN *=/s#=.*#=$with_msan#
+/^WITH_FUZZERS *=/s#=.*#=$with_fuzzers#
+/^SANITIZERS_CFLAGS *=/s#=.*#=$SANITIZERS_CFLAGS#
+/^MSAN_CFLAGS *=/s#=.*#=$MSAN_CFLAGS#
 /^SFLAGS *=/s#=.*#=$SFLAGS#
 /^LDFLAGS *=/s#=.*#=$LDFLAGS#
 /^LDSHARED *=/s#=.*#=$LDSHARED#
